### ISSUE TITLE
Failed to fetch plugin https://github.com/imransilvake/Cordova-Plugin-Sync-Cookies via registry.

### ISSUE THREAD

**Issue by leiwensu** [imransilvake/Cordova-Plugin-Sync-Cookies#1]
执行以下命令时，报错说拉取失败
`cordova plugin add https://github.com/imransilvake/Cordova-Plugin-Sync-Cookies`
报错信息如下：
`Failed to fetch plugin https://github.com/imransilvake/Cordova-Plugin-Sync-Cookies via registry. 
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module`
我的环境信息如下：
![image](https://user-images.githubusercontent.com/12728122/52551019-a6415080-2e15-11e9-9201-947d14b69af9.png)

**Comment by imransilvake** [comment]
which cordova version do you have installed?

Try to completely remove the plugin and give another try to:
`cordova plugin add https://github.com/imransilvake/Cordova-Plugin-Sync-Cookies`

**Comment by imransilvake** [comment]
**closing this issue.**

**Comment by mikeg0184** [comment]
I'm running into this issue as well.
